### ISSUE TITLE
Pydantic version above 1.10.2 breaks duqtools

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#566]
- Version is now fixed, but we should fix duqtools to work with upstream again

**Comment by stefsmeets** [comment]
I'm on `Version: 1.10.6` and I have not noticed any breakage. What is the error? Maybe it's just `1.10.{3..5}` that is bad?

**Comment by Marinmepfl** [comment]
The error is:

Traceback (most recent call last):
  File "/afs/eufus.eu/user/g/g2mmarin/.local/bin/duqtools", line 5, in <module>
    from duqtools.cli import cli_entry
  File "/afs/eufus.eu/g2itmuse/user/g2mmarin/spearhead/duqtools/src/duqtools/cli.py", line 9, in <module>
    from pydantic import ValidationError
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
    from .names import names
  File "pydantic/dataclasses.py", line 47, in init pydantic.dataclasses
    # | raise   | TypeError is raised.                    |
  File "pydantic/main.py", line 121, in init pydantic.main
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'
