### ISSUE TITLE
Pydantic error when launching duqduq setup

### ISSUE THREAD

**Issue by aaronkho** [duqtools/duqtools#639]
I launched the following command line argument:
`duqduq setup -i lsv_interpretive_qedgemod_data.csv -t duqtools.interpretive_qedgemod_template.yaml -l lsv_interpretive_qedgemod.log --dry-run`
from `/pfs/work/g2aho/lsv/` on the Gateway using 85d2bb8c (latest master commit).

I received the error:
```
Traceback (most recent call last):
  File "/afs/eufus.eu/user/g/g2aho/.local/bin/duqduq", line 8, in <module>
    sys.exit(cli_entry())
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/large_scale_validation/cli.py", line 20, in cli_entry
    cli()
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/cli.py", line 137, in callback
    func(**kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/large_scale_validation/cli.py", line 57, in cli_setup
    setup(**kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/large_scale_validation/setup.py", line 12, in setup
    substitute_templates(
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/setup.py", line 195, in substitute_templates
    Config.parse_raw(cfg)  # make sure config is valid
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/pydantic_yaml/mixin.py", line 275, in parse_raw
    res = cls.parse_obj(obj)  # type: ignore
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Config
system
  Discriminator 'name' is missing in value (type=value_error.discriminated_union.missing_discriminator; discriminator_key=name)
```

Perhaps something has changed in the template syntax?

**Comment by stefsmeets** [comment]
Yep, we revised the system definition. See https://duqtools.readthedocs.io/en/latest/large_scale_validation/#config-template

```
system:
  name: jetto
```

**Comment by aaronkho** [comment]
The change works
