### ISSUE TITLE
Missing config error with duqduq submit

### ISSUE THREAD

**Issue by aaronkho** [duqtools/duqtools#640]
I have run the following on Gateway, within `/pfs/work/g2aho/lsv/interpretive_qedgemod`:
```duqduq submit -p 'base/**' --array --max_jobs 10 --max_array_size 500 -l lsv_interpretive_qedgemod.log```

And received the following error:
```
Traceback (most recent call last):
  File "/afs/eufus.eu/user/g/g2aho/.local/bin/duqduq", line 8, in <module>
    sys.exit(cli_entry())
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/large_scale_validation/cli.py", line 20, in cli_entry
    cli()
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/cli.py", line 137, in callback
    func(**kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/large_scale_validation/cli.py", line 137, in cli_submit
    submit(**kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/large_scale_validation/submit.py", line 84, in submit
    submitter(job_queue, max_jobs=max_jobs, max_array_size=max_array_size)
TypeError: job_array_submitter() missing 1 required keyword-only argument: 'cfg'
```

As far as I can tell, there is no way to directly pass a config file through the CLI. Am I missing something?

**Comment by stefsmeets** [comment]
Nope, that's a bug. I'll get it fixed today.
