### ISSUE TITLE
duqtools dash no longer working on Gateway

### ISSUE THREAD

**Issue by aaronkho** [duqtools/duqtools#645]
I receive the following error when running `duqtools dash` on the Gateway, using the `firefox/latest` module for the browser.
```
Traceback (most recent call last):
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/dashboard/Plotting.py", line 5, in <module>
    from _shared import add_sidebar_logo, default_workdir, get_dataset
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/dashboard/_shared.py", line 28, in <module>
    @st.cache_data
AttributeError: module 'streamlit' has no attribute 'cache_data'
```

I am running the command on a directory without a `data.csv` or a `runs.yaml`. Does this affect anything? Or perhaps I am missing something else?

**Comment by stefsmeets** [comment]
Can you try `pip install -U streamlit`? I think you may be using an outdated version.

**Comment by aaronkho** [comment]
Updating my local installation of streamlit to 1.16.0 has fixed the aforementioned issue. However, now another one occurs:

When pointing to `/gss_efgw_work/work/g2aho/lsv/predictive_qlknn_qedgemod_test/uq/jet89730_id2/data.csv`, I get the following error:
```
Traceback (most recent call last):
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/dashboard/Plotting.py", line 25, in <module>
    handles = read_imas_handles_from_file(inp)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/utils.py", line 75, in read_imas_handles_from_file
    has_header = csv.Sniffer().has_header(f.read(1024))
  File "/gw/switm/python/3.10/lib/python3.10/csv.py", line 393, in has_header
    rdr = reader(StringIO(sample), self.sniff(sample))
  File "/gw/switm/python/3.10/lib/python3.10/csv.py", line 187, in sniff
    raise Error("Could not determine delimiter")
_csv.Error: Could not determine delimiter
```

Since the `data.csv` file is relatively short, I have pasted it here for your convenience:
```
,relative_location,user,db,shot,run
jet89730_id2.run_0000,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0000/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0001,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0001/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0002,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0002/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0003,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0003/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0004,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0004/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0005,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0005/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0006,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0006/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0007,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0007/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0008,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0008/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0009,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0009/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0010,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0010/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0011,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0011/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0012,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0012/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0013,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0013/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0014,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0014/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0015,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0015/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0016,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0016/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0017,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0017/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0018,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0018/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0019,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0019/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0020,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0020/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0021,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0021/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0022,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0022/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0023,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0023/imasdb,jet_lsvdb,89730,2
jet89730_id2.run_0024,,/gss_efgw_work/work/g2aho/jetto/runs/runlsv/predictive_qlknn_qedgemod/jet89730_id2/run_0024/imasdb,jet_lsvdb,89730,2
```

**Comment by stefsmeets** [comment]
Thanks for thinking about my convenience 😅

I believe `,,` is illegal. Try with removing the relative location column.

**Comment by aaronkho** [comment]
Ok, I have tried removing the column (including the corresponding header entry) and the same error occurs.

**Comment by stefsmeets** [comment]
Maybe, I'll investigate on Monday 👍

In the mean time, I think this should work-around the issue:
`index,user,db,shot,run`

**Comment by aaronkho** [comment]
The addition of the `index` header also did not work. The dashboard fix is not urgent as there are other plotting software I can use in the meantime, but it would be nice to show examples from the dashboard on my conference poster.

**Comment by stefsmeets** [comment]
This is odd, it seems to work with 8 entries, but when I add the 9th entry it errors out??
