### ISSUE TITLE
Dashboard "show error bars" fails when IDS "error_upper" field is empty

### ISSUE THREAD

**Issue by aaronkho** [duqtools/duqtools#651]
Is it possible to show entries with no "error_upper" data with zero error instead? This way the plotting tool does not crash if only one item has the field empty. Alternatively, the item can simply be omitted from the plot to not confuse the user with actual zero error.

```
Traceback (most recent call last):
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/dashboard/Plotting.py", line 56, in <module>
    source, time_var, grid_var, data_var = get_dataset(
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/dashboard/_shared.py", line 84, in get_dataset
    return _get_dataset(handles, variable, include_error=include_error)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 209, in wrapper
    return cached_func(*args, **kwargs)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 238, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 263, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 317, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/dashboard/_shared.py", line 61, in _get_dataset
    ds = handle.get_variables(variables=variables)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/ids/_handle.py", line 315, in get_variables
    ds = data_map.to_xarray(variables=var_models, **kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/ids/_mapping.py", line 370, in to_xarray
    raise EmptyVarError(
duqtools.ids._mapping.EmptyVarError: Variable 't_e_error_upper' contains empty data.
```

**Comment by stefsmeets** [comment]
So essentially this happens if you load a number of data sets, but one of the data sets misses the `_error_upper` field for the IDS you selected.

I agree that catching this error and falling back to showing no error bar would be a good way to handle this.
