### ISSUE TITLE
Dashboard/plots are broken with `altair>=5`

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#655]
Altair recently updated to version 5, and this breaks our dashboard. It's not clear to me why.

```python
Traceback (most recent call last):
  File "/afs/eufus.eu/g2itmuse/user/g2ssmee/duqtools/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/afs/eufus.eu/g2itmuse/user/g2ssmee/duqtools/src/duqtools/dashboard/Ploting.py", line 65, in <module>
    chart = alt_line_chart(source,
  File "/afs/eufus.eu/g2itmuse/user/g2ssmee/duqtools/src/duqtools/_plot_utils.py", line 89, in alt_line_chart
    select_step = alt.selection_single(name=z,
  File "/afs/eufus.eu/g2itmuse/user/g2ssmee/duqtools/.venv/lib/python3.10/site-packages/altair/utils/deprecation.py", line 66, in new_obj
    return obj(*args, **kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2ssmee/duqtools/.venv/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 714, in selection_single
    return _selection(type="point", **kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2ssmee/duqtools/.venv/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 441, in _selection
    return param(select=select, **param_kwds)
  File "/afs/eufus.eu/g2itmuse/user/g2ssmee/duqtools/.venv/lib/python3.10/site-packages/altair/vegalite/v5/api.py", line 410, in param
    parameter.param = core.SelectionParameter(
TypeError: altair.vegalite.v5.schema.core.SelectionParameter() got multiple values for keyword argument 'value'
```

See also this post on SO which reports a similar issue:
https://stackoverflow.com/questions/77060740/how-to-fix-altair-error-when-code-appears-to-be-right

**Comment by stefsmeets** [comment]
I pinned altair to v4 in 0f1ca2e in the mean time.
