### ISSUE TITLE
Installation on JET system

### ISSUE THREAD

**Issue by Marinmepfl** [duqtools/duqtools#733]
I tried cloning the duqtools on the JET system, nx001.jetdata.eu.
With `pip install duqtools` I get the following error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ymmsl 0.13.0 requires ruamel.yaml!=0.17.5,<=0.17.21, but you have ruamel-yaml 0.17.40 which is incompatible.
yatiml 0.10.0 requires ruamel.yaml!=0.17.5,<=0.17.21,>=0.15.71, but you have ruamel-yaml 0.17.40 which is incompatible.
```

And the logging errors:
```
--- Logging error ---
Traceback (most recent call last):
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_vendor/rich/console.py", line 1752, in print
    extend(render(renderable, render_options))
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_vendor/rich/console.py", line 1390, in render
    for render_output in iter_render:
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_vendor/rich/segment.py", line 245, in split_lines
    for segment in segments:
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_vendor/rich/console.py", line 1368, in render
    renderable = rich_cast(renderable)
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_internal/utils/entrypoints.py", line 60, in get_best_invocation_for_this_pip
    os.path.join(binary_prefix, exe_name),
  File "/usr/local/depot/Python-3.7/lib/python3.7/genericpath.py", line 97, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/depot/Python-3.7/bin/pip3.7'
```

```
Call stack:
  File "/home/sim/jintrac-pythontools/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 101, in main
    return self._main(args)
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    self.handle_pip_version_check(options)
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 148, in handle_pip_version_check
    pip_self_version_check(session, options)
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_internal/self_outdated_check.py", line 237, in pip_self_version_check
    logger.info("[present-rich] %s", upgrade_prompt)
  File "/usr/local/depot/Python-3.7/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/depot/Python-3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/depot/Python-3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/depot/Python-3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/depot/Python-3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/home/sim/jintrac-pythontools/lib/python3.7/site-packages/pip/_internal/utils/logging.py", line 179, in emit
    self.handleError(record)
Message: '[present-rich] %s'
```
The tools are installed, but when I try to `import ImasHandle` I still get the error
```
Traceback (most recent call last):
  File "tcv_marius.py", line 1, in <module>
    from prepare_im_runs import *
  File "/home/marinm/fusion-scripts/prepare_im_runs.py", line 29, in <module>
    import setup_nbi_input
  File "/home/marinm/fusion-scripts/setup_nbi_input.py", line 6, in <module>
    from duqtools.api import ImasHandle
  File "/home/marinm/.local/lib/python3.7/site-packages/duqtools/api.py", line 22, in <module>
    from .ids import (
  File "/home/marinm/.local/lib/python3.7/site-packages/duqtools/ids/__init__.py", line 3, in <module>
    from ._handle import ImasHandle
  File "/home/marinm/.local/lib/python3.7/site-packages/duqtools/ids/_handle.py", line 13, in <module>
    from ..config import lookup_vars
  File "/home/marinm/.local/lib/python3.7/site-packages/duqtools/config/__init__.py", line 1, in <module>
    from ._config import Config, cfg
  File "/home/marinm/.local/lib/python3.7/site-packages/duqtools/config/_config.py", line 3, in <module>
    from ..schema.cli import ConfigModel
  File "/home/marinm/.local/lib/python3.7/site-packages/duqtools/schema/__init__.py", line 2, in <module>
    from ._dimensions import IDSOperation, IDSOperationDim, JettoOperation, OperationDim
  File "/home/marinm/.local/lib/python3.7/site-packages/duqtools/schema/_dimensions.py", line 3, in <module>
    from typing import Literal, Union
ImportError: cannot import name 'Literal' from 'typing' (/usr/local/depot/Python-3.7/lib/python3.7/typing.py)
```

How do I solve this?

**Comment by v1kko** [comment]
Hi @Marinmepfl any progress on this?

**Comment by Marinmepfl** [comment]
I think the default python at JET is still 3.7 and I have not tried to use a local version yet. I found a way around that did not involve Duqtools and now the gateway is back online, so I think I will just wait till python is upgraded...
